import argparse
from pathlib import Path

import pandas as pd


def normalise_path(value: str) -> str:
    return str(value or "").strip()


def main():
    parser = argparse.ArgumentParser(
        description="Compare gold labels against master gallery category predictions."
    )
    parser.add_argument("gold_labels_csv", help="Gold labels CSV, e.g. gold_labels_v1.csv")
    parser.add_argument(
        "master_gallery_images_csv",
        help="master_gallery_images.csv generated by consolidate_themes_dev.py",
    )
    parser.add_argument(
        "--output",
        default="gold_label_evaluation.csv",
        help="Output comparison CSV",
    )
    parser.add_argument(
        "--confusion-output",
        default="gold_label_confusion_matrix.csv",
        help="Output confusion matrix CSV",
    )
    args = parser.parse_args()

    gold_path = Path(args.gold_labels_csv).expanduser().resolve()
    pred_path = Path(args.master_gallery_images_csv).expanduser().resolve()
    output_path = Path(args.output).expanduser().resolve()
    confusion_path = Path(args.confusion_output).expanduser().resolve()

    gold = pd.read_csv(gold_path)
    pred = pd.read_csv(pred_path)

    required_gold = {"path", "correct_category"}
    required_pred = {"path", "primary_master_category"}

    missing_gold = required_gold - set(gold.columns)
    missing_pred = required_pred - set(pred.columns)

    if missing_gold:
        raise ValueError(f"Gold labels CSV missing columns: {sorted(missing_gold)}")
    if missing_pred:
        raise ValueError(f"Master gallery CSV missing columns: {sorted(missing_pred)}")

    gold["path_key"] = gold["path"].apply(normalise_path)
    pred["path_key"] = pred["path"].apply(normalise_path)

    pred_small_cols = [
        "path_key",
        "primary_master_category",
        "mapping_confidence",
        "display_theme_name",
        "theme_name",
        "review_flags",
        "mapping_evidence",
    ]
    pred_small_cols = [c for c in pred_small_cols if c in pred.columns]

    pred_small = pred[pred_small_cols].copy()
    pred_small = pred_small.rename(columns={
        "primary_master_category": "predicted_category"
    })

    merged = gold.merge(pred_small, on="path_key", how="left")

    merged["is_matched"] = merged["predicted_category"].notna()
    merged["is_correct"] = merged["correct_category"] == merged["predicted_category"]

    matched = merged[merged["is_matched"]].copy()
    unmatched = merged[~merged["is_matched"]].copy()
    errors = matched[~matched["is_correct"]].copy()

    total_gold = len(merged)
    total_matched = len(matched)
    total_unmatched = len(unmatched)
    total_correct = int(matched["is_correct"].sum())
    accuracy = total_correct / total_matched if total_matched else 0

    print()
    print("Gold label evaluation")
    print("---------------------")
    print(f"Gold rows:        {total_gold}")
    print(f"Matched rows:     {total_matched}")
    print(f"Unmatched rows:   {total_unmatched}")
    print(f"Correct matched:  {total_correct}")
    print(f"Accuracy:         {accuracy:.3f}")

    if total_unmatched:
        print()
        print("Warning: unmatched gold rows exist. Check path differences.")

    print()
    print("Largest error patterns:")
    if errors.empty:
        print("  None")
    else:
        error_counts = (
            errors.groupby(["correct_category", "predicted_category"])
            .size()
            .reset_index(name="count")
            .sort_values("count", ascending=False)
        )
        for _, row in error_counts.head(12).iterrows():
            print(
                f"  {row['correct_category']} -> {row['predicted_category']}: {row['count']}"
            )

    output_cols = [
        "path",
        "file",
        "correct_category",
        "predicted_category",
        "is_correct",
        "mapping_confidence",
        "display_theme_name",
        "theme_name",
        "review_flags",
        "mapping_evidence",
        "notes",
    ]
    output_cols = [c for c in output_cols if c in merged.columns]

    merged[output_cols].to_csv(output_path, index=False)

    if not matched.empty:
        confusion = pd.crosstab(
            matched["correct_category"],
            matched["predicted_category"],
            margins=True,
        )
        confusion.to_csv(confusion_path)
    else:
        pd.DataFrame().to_csv(confusion_path, index=False)

    print()
    print(f"Comparison CSV:   {output_path}")
    print(f"Confusion matrix: {confusion_path}")


if __name__ == "__main__":
    main()
